
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=development
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=development
      - DATABASE_HOST=database.service.pinning.internal
    networks:
      - internal
    depends_on:
      - database.service.pinning.internal

  database.service.pinning.internal:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=development

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
