
version: '3'
services:
  app:
    image: ipfsshipyard/ipfs_dht_explorer:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=production
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=development
      - DATABASE_HOST=database.service.explorer.internal
      - GEO_IP_DIR=/usr/share/GeoIP
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MAX_THREADS=5
      - REDIS_URL=redis://redis.service.explorer.internal
    networks:
      - internal
    depends_on:
      - database.service.explorer.internal
      - redis.service.explorer.internal
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'

  database.service.explorer.internal:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=development
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

  geoipupdate:
    container_name: geoipupdate
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=416437
      - GEOIPUPDATE_LICENSE_KEY=Iezh99N2ZFDt1jCI
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoIP2-Domain'
      - GEOIPUPDATE_FREQUENCY=168
    networks:
      - geoipupdate
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'

  crawler:
    image: ipfsshipyard/libp2p-dht-scrape-client:latest

  redis.service.explorer.internal:
    image: redis:6.0-alpine
    networks:
      - internal

volumes:
  pg_data:
  geoipupdate_data:
    driver: local

networks:
  geoipupdate:
  internal:
    driver: bridge
