
version: '3'
services:
  app:
    image: ipfsshipyard/ipfs_dht_explorer:latest
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=production
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=development
      - DATABASE_HOST=database.service.explorer.internal
      - GEO_IP_DIR=/usr/share/GeoIP
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MAX_THREADS=10
      - REDIS_URL=redis://redis.service.explorer.internal
      - IPFS_URL=ipfs.service.explorer.internal
      - RAILS_LOG_TO_STDOUT=true
    networks:
      - internal
    depends_on:
      - database.service.explorer.internal
      - redis.service.explorer.internal
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
        max-file: "5"

  database.service.explorer.internal:
    image: postgres:9.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=development
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

  geoipupdate:
    container_name: geoipupdate
    image: maxmindinc/geoipupdate
    restart: unless-stopped
    environment:
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoIP2-Domain'
      - GEOIPUPDATE_FREQUENCY=168
    networks:
      - geoipupdate
    volumes:
      - 'geoipupdate_data:/usr/share/GeoIP'
    env_file:
      - .env

  crawler:
    image: ipfsshipyard/libp2p-dht-scrape-client:latest

  redis.service.explorer.internal:
    image: redis:6.0-alpine
    networks:
      - internal
    volumes:
      - redis_data:/data

  ipfs.service.explorer.internal:
    image: ipfs/go-ipfs:latest
    networks:
      - internal
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
      - IPFS_LOGGING=debug
      - IPFS_LOGGING_FMT=nocolor
    volumes:
      - ./data/ipfs:/ipfsdata
    ports:
      - "4001:4001"
      - "4003:4003"
      - "8080:8080"
      - "8081:8081"
      - "5001:5001"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
        max-file: "5"        

volumes:
  pg_data:
  redis_data:
  geoipupdate_data:
    driver: local

networks:
  geoipupdate:
  internal:
    driver: bridge
