discover_connected_peers:
  cron: "0 */1 * * *"
  class: "DiscoverConnectedPeersWorker"
  queue: critical

dial_incomplete_nodes:
  cron: "30 */1 * * *"
  class: "DialIncompleteNodesWorker"
  queue: critical
