discover_connected_peers:
  cron: "0 */1 * * *"
  class: "DiscoverConnectedPeersWorker"
  queue: critical

dial_secio_nodes:
  cron: "15 */1 * * *"
  class: "DialSecioNodesWorker"
  queue: critical

dial_incomplete_nodes:
  cron: "30 */1 * * *"
  class: "DialIncompleteNodesWorker"
  queue: critical

detect_content_types:
  cron: "45 */1 * * *"
  class: "DetectContentTypesWorker"
  queue: critical

export_nodes:
  cron: "0 0 * * 0"
  class: "ExportNodesWorker"
  queue: critical
