discover_connected_peers:
  cron: "0 */4 * * *"
  class: "DiscoverConnectedPeersWorker"
  queue: critical

dial_secio_nodes:
  cron: "15 */2 * * *"
  class: "DialSecioNodesWorker"
  queue: critical

dial_incomplete_nodes:
  cron: "30 */3 * * *"
  class: "DialIncompleteNodesWorker"
  queue: critical

detect_content_types:
  cron: "45 */1 * * *"
  class: "DetectContentTypesWorker"
  queue: critical

export_nodes:
  cron: "0 0 * * 0"
  class: "ExportNodesWorker"
  queue: critical

export_cids:
  cron: "0 4 * * 0"
  class: "ExportCidsWorker"
  queue: critical

export_wants:
  cron: "0 8 * * *"
  class: "ExportWantsWorker"
  queue: critical

repo_gc:
  cron: "0 16 * * *"
  class: "IpfsRepoGcWorker"
  queue: critical
